services:
  bot:
    image: shashibot:latest
    environment:
        DISCORD_SECRET: "INSERT SECRET_HERE"
        DISCORD_TOKEN: "DITTO"
        DISCORD_CLIENT_ID: "DITTO"
        DISCORD_GUILD_ID: "DITTO"

        FIREBASE_API_KEY: "DITTO"
        FIREBASE_AUTHDOMAIN: "DITTO"
        FIREBASE_PROJECTID: "DITTO"
        FIREBASE_STORAGEBUCKET: "DITTO"
        FIREBASE_MESSAGINGSENDERID: "DITTO"
        FIREBASE_APPID: "DITTO"
        FIREBASE_MEASUREMENTID: "DITTO"
        
        LLM_API_BASEURL: "http://llm:8000/v1"
        LLM_API_KEY: "NOT NEEDED"
  llm:
    image: shashillm:latest
    volumes:
      - ./models:/models
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "8000:8000"
